version: '2'

services:

  backup-unit:
    image: s3-cron-backup:site.1.0.0
    # env_file contains info regarding s3 bucket (name, api-keys, etc).
    env_file:
      - .env
    environment:
      - BACKUP_NAME=wordpress
#      - CRON_WEEKLY_SCHEDULE="00 7 * * 6"
#      - CRON_MONTHLY_SCHEDULE="00 7 1 * *"
#      - CRON_YEARLY_SCHEDULE="00 7 1 1 *"
      - CRON_WEEKLY_SCHEDULE=50 13 * * *
      - CRON_MONTHLY_SCHEDULE=51 13 * * *
      - CRON_YEARLY_SCHEDULE=52 13 * * *
    volumes:
      - ./data:/data/tmp:ro
